name: home-link

options:
  usesTabs: true
  tabWidth: 2
  indentWidth: 2

settings:
  configs:
    Debug:
      GCC_PREPROCESSOR_DEFINITIONS:
    Release:
      GCC_PREPROCESSOR_DEFINITIONS: NDEBUG=1
  base:
    GCC_C_LANGUAGE_STANDARD: c11
    CLANG_CXX_LANGUAGE_STANDARD: c++20
    USE_HEADERMAP: false
    GCC_WARN_PEDANTIC: true
    GCC_TREAT_WARNINGS_AS_ERRORS: true

include:
  - home-link/home-link.yml
  - cpp-network/cpp-network/cpp-network.yml
  - examples/examples.yml
